# Generated by Django 3.2.4 on 2021-06-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=10)),
                ('categoria', models.CharField(choices=[('MJ', 'Mujer'), ('HM', 'Hombre'), ('NN', 'Niño')], max_length=2)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
